Beheerdershandleiding
kadaster-labs/sensrnet-home pull request #273
Opened 2021-12-08 20:40 UTC by kad-vossef

t.b.v. review

2021-12-09 10:52 UTC, marcvanandel requested changes
Toch een paar comments ... 😇

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +# Handleiding Beheerders SensRNet (Concept) <img src="https://github.com/kadaster-labs/sensrnet-home/blob/Beheerdershandleiding/docs/img/AdminManualNL/EindhovenLogo.png" width="80" align="right">
de `src` kan toch kort? (net zoals de andere plaatjes hieronder?)

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +# Handleiding Beheerders SensRNet (Concept) <img src="https://github.com/kadaster-labs/sensrnet-home/blob/Beheerdershandleiding/docs/img/AdminManualNL/EindhovenLogo.png" width="80" align="right">
Naar mijn idee is dit een 'SensRNet Gebruikershandleiding' en mag het `UserManualNL.md` heten als bestand. Dat de 'user' hier een beheerder is, lijkt mij niet zo relevant. Je kunt als 'user' / gebruiker ook de rol `Admin` hebben en er is ook nog (technisch) beheerder van de software. Daarom vind ik dit meer een gebruiker dan een beheerder.

'Beheerder van sensor metadata' is 'gebruiker in SensRNet Registry Node' ... Dat bedoel ik eigenlijk te zeggen 😉

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +## In de tool <a name="paragraaf1"></a>
Dit wordt automatisch al een header id, die je kunt 'linken'. De link wordt dan `#in-de-tool`. Deze zijn dan weer in de TOC (table of contents) te gebruiken

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +> _LET OP: dit is een CONCEPT document dat zal worden aangevuld op basis van de resultaten van de [pilots](https://kadaster-labs.github.io/sensrnet-home/Pilots/)._
De link kan eenvoudiger: `Pilots.md` is voldoende. De rest van de link wordt automatisch aangevuld 😉

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +> _De initiële versie van dit document is gemaakt door de [gemeente Eindhoven](https://www.eindhoven.nl/). Opmerkingen of vragen over deze handleiding? Mail data@eindhoven.nl._
Ik zou hier liever iets zeggen als:

> Met dank aan Gemeente Eindhoven voor de eerste opzet van deze handleiding

En apart iets over feedback:

> Feedback, verbeteringen zijn welkom of kom met ons in contact. Zie [Contribution](../#connect)

Mocht Eindhoven graag in die 'connect' opgenomen willen worden, dan lijkt dat me de beste plek daarvoor, niet?

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +# Inhoudsopgave
De inhoudsopgave kan overigens helemaal weg. Dat wordt automatisch gegenereerd op basis van de content van deze pagina in de publicatie van de documentatie 💪

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +## Resultaat
'Publicatie' vind ik beter dan 'Resultaat' (persoonlijke mening) Of misschien 'Resultaat voor de burger' (zie ook volgende comments)

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +Zo. Je sensoren zijn opgevoerd. Maar hoe ziet dit er voor gebruikers uit? Zij kunnen publieke sensoren bekijken in de viewers:
'gebruikers' vervangen door 'de burger'.

En 'zij kunnen de sensoren bekijken in de publieke viewers' (dus 'publieke' verschuiven naar viewer ipv sensoren ... )

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +  > [Demo omgeving: Viewer](https://demo.sensorenregister.nl/viewer)
[Central Viewer (productie)]() | [Centrale Viewer (demo)]()

vind ik mooier ...

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +  > [Demo omgeving](https://demo.sensorenregister.nl/api/#/)
[Registy Node API (demo)]()

De 'productie API' ... is die van de Central Viewer ... en dat is GEEN Registry Node. Die zouden we hier niet moeten noemen...

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +  > [Productie omgeving](https://viewer.sensorenregister.nl/api/#/)
Dit is GEEN Registry Node API, maar de Central Viewer API. Die moet hier niet genoemd worden ...

2021-12-09 10:52 UTC, marcvanandel commented on docs/AdminManualNL.md
> +![SensRNet-Applicatie](img/AdminManualNL/SensRNet_API3.png)
Ik zie hier nergens een link naar het script. Dat zou IN dit PR kunnen worden toegevoegd, lijkt mij? Net zoals de Excel als template, niet?

2021-12-09 12:19 UTC, kad-vossef commented on docs/AdminManualNL.md
> +![SensRNet-Applicatie](img/AdminManualNL/SensRNet_API3.png)
Ik heb al je commentaar verwerkt (en overgenomen). De laatste is even de vraag hoe we dit toevoegen. Graag even overleg.

2021-12-09 12:26 UTC, marcvanandel commented on docs/AdminManualNL.md
> +![SensRNet-Applicatie](img/AdminManualNL/SensRNet_API3.png)
Ik dacht dat Celine het script in #176 toegevoegd ... toch? Daar kan ie uit gehaald worden en toegevoegd in deze PR?

2021-12-09 12:53 UTC, kad-vossef commented
See Excel template (also in #176):

[FME scripts bulk Opvoer en Verwijderen.zip](https://github.com/kadaster-labs/sensrnet-home/files/7685176/FME.scripts.bulk.Opvoer.en.Verwijderen.zip)

2021-12-09 14:42 UTC, kad-bloemy commented
Ik heb het plaatje voor het menu nagemaakt. Misschien wil je deze testen? Als deze beter is, wil ik er wel meer repliceren.
![SensRNet_Appl1_YB](https://user-images.githubusercontent.com/72614432/145417206-8f0c77ed-badf-4953-8bb2-89e2cae61e52.png)

2021-12-09 14:45 UTC, kad-vossef commented
Zeker goed Yolanda! Als je tijd hebt dan maakt dat het document een stuk leesbaarder!

2021-12-15 09:23 UTC, merged

2021-12-20 16:37 UTC, CelineJansen commented
Heb inmiddels ook een basis staan voor het bewerken van gegevens en het ophalen van een stand voorafgaande hieraan.

Let op: deze scripts zijn wederom puur ter inspiratie. Het betreft geen afgewerkte eindproducten: ze zijn niet uitvoerig getest, er wordt uitgegaan van een valide input (geen/nauwelijks fout afhandeling), en e.e.a. berust op enkele aannames (bijvoorbeeld dat er niet datastromen met precies dezelfde attributen bij een sensor kunnen horen).
Praktijktest zullen uitwijzen waar bijgeschaafd moet worden.
Er volgt nog een nieuwe versie voor het opvoeren van een ObservedArea op de kaart wanneer dit mogelijk is met de API van de demo-omgeving (https://github.com/kadaster-labs/sensrnet-registry-frontend/issues/192). De basis hiervoor heb ik wel al staan maar daar kan ik nog helemaal niks aan testen en wacht ik dus nog even mee.

[Scripts en input SensorenAPI.zip](https://github.com/kadaster-labs/sensrnet-home/files/7746705/Scripts.en.input.SensorenAPI.zip)