Kad bloemy patch 1
kadaster-labs/sensrnet-home pull request #292
Opened 2022-02-04 14:06 UTC by kad-bloemy

Ik heb eerst Definitions.rst aangepast, maar omdat ik lekker bezig was, heb ik ook een Definitions.md gemaakt. Is mooier. Tevens alle verwijzingen naar .rst gewijzigd naar .md.

2022-02-08 08:33 UTC, kad-busses requested changes
Goed werk, ziet er inderdaad goed uit zo. Met het toevoegen van de .md zou de .rst er mijns inziens uit kunnen, dan hoeven we de definities maar op 1 plek bij te houden. 

Ben een paar kleine puntjes tegengekomen, zou je die nog willen aanpassen?

2022-02-08 08:33 UTC, kad-busses commented on docs/Definitions.md
> + These definitions of fields are part of the SensRNet [datamodel](Model.md). If availible, we've used the definitions of OGC's [SensorThingsAPI](https://www.ogc.org/standards/sensorthings); the other
"... our own's" -> "... our own"

2022-02-08 08:33 UTC, kad-busses commented on docs/Definitions.rst
> +| Email              |                       | E-mail                        | Yes    | The   e-mail address by which the legal entity can be contacted.                              | Het   e-mailadr
Het linkje naar deze Excel werkt niet, moet dat `Waardelijst_Public_E-mail-mask_` zijn?

2022-02-08 08:47 UTC, marcvanandel requested changes
Helaas ... dit werkt niet. Dit werkt wel als je de `Definitions.md` in GitHub bekijkt ... maar dit werkt niet in de documentatie publicatie. Dat is een andere 'engine' die van Markdown de vertaling naar HTML maakt ... en deze omvang van de tabel werkt niet goed 😢 

Ik stel voor om voor dit moment de hele tabel (weer terug -> sorry) te transformeren naar MS Excel en deze als bestand toe te voegen aan de repo. En natuurlijk dan een linkje naar het bestand in de `Model.md` pagina ...

2022-02-08 09:04 UTC, kad-busses commented
Goeie @marcvanandel, dat had ik niet gecheckt, jammer dat die rendering niet goed werkt. Zouden we, in plaats van alles weer in Excel te stoppen, niet simpelweg een linkje toevoegen naar de GitHub pagina voor de definities?

2022-02-08 09:39 UTC, marcvanandel commented
Yup. Dat kan zeker! En zo was het ook (alleen was het reStructuredText ipv Markdown ;-)

2022-02-08 10:49 UTC, kad-bloemy commented
Dank voor het commentaar. Voorgestelde aanpassingen van Stefan aangebracht. De link naar het E-mail mask was al verbeterd, maar kennelijk niet in jullie versie.  Moet ik nu een nieuw pull-request maken?

2022-02-08 12:52 UTC, kad-bloemy commented on docs/Definitions.rst
> +| Email              |                       | E-mail                        | Yes    | The   e-mail address by which the legal entity can be contacted.                              | Het   e-mailadr
In mijn versie was dat al aangepast.

2022-02-08 12:52 UTC, kad-bloemy commented on docs/Definitions.md
> + Not necessarily the same as the ResultTime. May be an interval or an instant time, or some other compound temporal entity" |                           |                             |            |
aangepast

2022-02-08 12:53 UTC, kad-bloemy commented on docs/Definitions.md
> + These definitions of fields are part of the SensRNet [datamodel](Model.md). If availible, we've used the definitions of OGC's [SensorThingsAPI](https://www.ogc.org/standards/sensorthings); the other
Aangepast

2022-02-08 12:53 UTC, kad-bloemy commented on docs/Definitions.md
> + PhenomenonTime                                                                                                             | PhenomenonTime            | Tijdsperiode waarneming     | No         | Th
Aangepast

2022-02-17 14:16 UTC, marcvanandel commented
Als we `Definitions.rst` vervangen door iets anders (bijv. een verbeterde `Definitions.md`) dan moeten we niet vergeten om de .rst wel te verwijderen ... (en links daar naartoe ook aan te passen)

2022-02-17 14:49 UTC, kad-bloemy commented
@marcvanandel Ik had in mijn branch volgens mij al alle linkjes aangepast naar .md, behalve die in de documentatie publicatie.

2022-03-10 09:41 UTC, marcvanandel commented
Ik denk dat het zo wel goed (genoeg) is ... Zullen we 'm mergen (incl. squash!! 😉 )

2022-03-10 09:42 UTC, marcvanandel approved these changes

2022-03-10 09:45 UTC, merged