Update Deployment.md
kadaster-labs/sensrnet-home pull request #80
Opened 2020-11-18 11:23 UTC by RickSchager

[Gemeente Eindhoven - Azure Landing Zone TO v0.97.pdf](https://github.com/kadaster-labs/sensrnet-home/files/5559656/Gemeente.Eindhoven.-.Azure.Landing.Zone.TO.v0.97.pdf)
Added ideas 4 Azure Landing Zone cookbook.

2020-11-18 11:28 UTC, marcvanandel requested changes

2020-11-18 11:28 UTC, marcvanandel commented on docs/Deployment.md
> +For the MVP pilot group BrabantStad, we are envisioning SensRNet as a Service, based on an Azure Landing Zone [ALZ} 'cookbook'.
Nice! Misschien nog even de `}` vervangen door een `)` ? 😉 

En een extra enter voor deze tekst zodat het een aparte alinea wordt ... ?

2020-11-18 15:27 UTC, RickSchager reviewed
Fixed typo and suggestions

2020-11-18 15:28 UTC, RickSchager commented
Fixed typo and suggetions

2020-11-18 15:30 UTC, RickSchager commented
knoppen werken vreemd...
zie weer een merge req?


Met een vriendelijke groet,

Rick Schager
Burgemeester Custerslaan 17
6373 TP  Landgraaf

+31 6 3715 6986
+31 6 2118 0205


rick.schager@gmail.com




Op wo 18 nov. 2020 om 12:28 schreef Marc van Andel <notifications@github.com
>:

> *@marcvanandel* requested changes on this pull request.
> ------------------------------
>
> In docs/Deployment.md
> <https://github.com/kadaster-labs/sensrnet-home/pull/80#discussion_r526013712>
> :
>
> > @@ -6,6 +6,8 @@ These containers are designed to be run on [Kubernetes](https://kubernetes.io/),
>
>  Kubernetes can be deployed in your own datacenter or can be purchased at one of the cloud providers.
>
>
>
>  Currently only [Microsoft Azure](https://azure.microsoft.com/nl-nl/overview/) managed Kubernetes Service, [AKS](#aks), is described and supported by the development team.
>
> +For the MVP pilot group BrabantStad, we are envisioning SensRNet as a Service, based on an Azure Landing Zone [ALZ} 'cookbook'.
>
>
> Nice! Misschien nog even de } vervangen door een ) ? 😉
>
> En een extra enter voor deze tekst zodat het een aparte alinea wordt ... ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kadaster-labs/sensrnet-home/pull/80#pullrequestreview-533351191>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG23SDYTKJZICQ25V2CMCY3SQOVVXANCNFSM4TZ22WXQ>
> .
>

2020-11-18 16:30 UTC, marcvanandel commented on docs/Deployment.md
> +# Azure Landing Zone [ALZ] 4 MVP pilot BrabantStad
Sorry to bug you ... 😬 maar ik vind de header niet echt wat toevoegen. Jij wel?

2020-11-18 16:49 UTC, RickSchager commented
Net zo veel als alle andere headsets
Commit or not , tour call

On Wed, 18 Nov 2020, 17:30 Marc van Andel, <notifications@github.com> wrote:

> *@marcvanandel* commented on this pull request.
> ------------------------------
>
> In docs/Deployment.md
> <https://github.com/kadaster-labs/sensrnet-home/pull/80#discussion_r526227767>
> :
>
> > @@ -6,7 +6,10 @@ These containers are designed to be run on [Kubernetes](https://kubernetes.io/),
>
>  Kubernetes can be deployed in your own datacenter or can be purchased at one of the cloud providers.
>
>
>
>  Currently only [Microsoft Azure](https://azure.microsoft.com/nl-nl/overview/) managed Kubernetes Service, [AKS](#aks), is described and supported by the development team.
>
> -For the MVP pilot group BrabantStad, we are envisioning SensRNet as a Service, based on an Azure Landing Zone [ALZ} 'cookbook'.
>
> +
>
> +# Azure Landing Zone [ALZ] 4 MVP pilot BrabantStad
>
>
> Sorry to bug you ... 😬 maar ik vind de header niet echt wat toevoegen.
> Jij wel?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/kadaster-labs/sensrnet-home/pull/80#pullrequestreview-533630153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG23SD7S65EGVWFHEAOTGGTSQPZDNANCNFSM4TZ22WXQ>
> .
>

2020-11-19 07:34 UTC, marcvanandel approved these changes

2020-11-19 07:35 UTC, merged